# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
      ('user', '0001_create_user_table')
    ]

    operations = [
      migrations.RunSQL(
        """CREATE TABLE notification (
            notification_id INT AUTO_INCREMENT PRIMARY KEY,
            text VARCHAR(500),
            url VARCHAR(500),
            user_id INT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES user(user_id)
                ON UPDATE CASCADE
                ON DELETE CASCADE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );""",
        "DROP TABLE notification"
      )
    ]
