# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_add_num_words_article_table'),
    ]

    operations = [
      migrations.RunSQL("""
        ALTER TABLE article
        ADD COLUMN preview_x_frame_options VARCHAR(500)
        ;""",
        """
        ALTER TABLE article
        DROP COLUMN preview_x_frame_options
        """
      )
    ]
