# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
      migrations.RunSQL(
        """CREATE TABLE tag (
            tag_id INT AUTO_INCREMENT PRIMARY KEY,
            label VARCHAR(50) NOT NULL,
            image VARCHAR(500) NOT NULL
        );""",
        "DROP TABLE tag"
      )
    ]
