# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
      ('user', '0001_init_entity_table')
    ]

    operations = [
      migrations.RunSQL(
        """CREATE TABLE channel (
          channel_id INT AUTO_INCREMENT PRIMARY KEY,
          user_id INT,
          title VARCHAR(100) NOT NULL,
          description VARCHAR(500) NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (user_id) REFERENCES user (user_id)
              ON UPDATE CASCADE
              ON DELETE CASCADE
        );""",
        "DROP TABLE channel"
      )
    ]
