# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_create_channel_table'),
        ('channel', '0002_create_channel_tag_tables'),
    ]

    operations = [
    	migrations.RunSQL("""
            ALTER TABLE channel
            ADD COLUMN num_subscribers INT NOT NULL;
        """,
        """
            ALTER TABLE channel
            DROP COLUMN num_subscribers;
        """
        )
    ]
