# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_modify_channel_table'),
    ]

    operations = [
    	migrations.RunSQL("""
            ALTER TABLE channel
            MODIFY COLUMN num_subscribers INT NOT NULL DEFAULT 0;
        """,
        """
            ALTER TABLE channel
            MODIFY COLUMN num_subscribers INT NOT NULL;
        """
        )
    ]
