# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
      migrations.RunSQL(
        """CREATE TABLE user (
            user_id INT AUTO_INCREMENT PRIMARY KEY,
            facebook_id VARCHAR(20) NOT NULL,
            email VARCHAR(100) UNIQUE NOT NULL,
            name VARCHAR(100), 
            photo VARCHAR(500),
            bio VARCHAR(500),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );""",
        "DROP TABLE user;"
      )
    ]
