# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_create_user_rship_tables'),
    ]

    operations = [
      migrations.RunSQL(
        """ALTER TABLE user
            MODIFY COLUMN facebook_id VARCHAR(20) UNIQUE NOT NULL,
            MODIFY COLUMN email VARCHAR(100);
        """,
        """ALTER TABLE user
            MODIFY COLUMN facebook_id VARCHAR(20) NOT NULL,
            MODIFY COLUMN email VARCHAR(100) UNIQUE NOT NULL;
        """
      )
    ]

