# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_create_channel_table'),
        ('user', '0005_follow_notification_trigger'),
    ]

    operations = [
    	migrations.RunSQL("""
            CREATE TRIGGER subscribe_channel AFTER INSERT ON user_follows_channel
            FOR EACH ROW
            BEGIN
            Set @subbed_chnn = (SELECT channel_id FROM user_follows_channel WHERE created_at = (SELECT max(created_at) FROM user_follows_channel));
            UPDATE channel SET num_subscribers = num_subscribers + 1 WHERE channel_id = @subbed_chnn;
            END;
        """,
        "DROP TRIGGER subscribe_channel"
      )
    ]