# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_create_channel_table'),
        ('user', '0006_subscribe_channel_trigger'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE TRIGGER unsubscribe_channel AFTER DELETE ON user_follows_channel
            FOR EACH ROW
            UPDATE channel SET num_subscribers = num_subscribers - 1 WHERE channel_id = OLD.channel_id;
        """,
        "DROP TRIGGER unsubscribe_channel"
      )
    ]
