# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_modify_likes_trigger'),
    ]

    operations = [

    	migrations.RunSQL(
        "DROP TRIGGER subscribe_channel",
        """
            CREATE TRIGGER subscribe_channel AFTER INSERT ON user_follows_channel
            FOR EACH ROW
            BEGIN
            Set @subbed_chnn = (SELECT channel_id FROM user_follows_channel WHERE created_at = (SELECT max(created_at) FROM user_follows_channel));
            UPDATE channel SET num_subscribers = num_subscribers + 1 WHERE channel_id = @subbed_chnn;
            INSERT INTO notification (type, type_id, channel_id, user_id, is_read, type_user_id)
            VALUES ('channel', NEW.channel_id, NEW.channel_id, (
                SELECT user_id from channel WHERE channel_id = NEW.channel_id), false, NEW.user_id);
            END;
        """,
        ),

        migrations.RunSQL(
        """
            CREATE TRIGGER follow_notification AFTER INSERT ON user_follows_channel
            FOR EACH ROW
            BEGIN
            	SET @subbed_chnn = (SELECT channel_id FROM user_follows_channel
            		WHERE created_at = (SELECT max(created_at) FROM user_follows_channel));
            	UPDATE channel SET num_subscribers = num_subscribers + 1 WHERE channel_id = @subbed_chnn;
            	INSERT INTO notification (type, type_id, channel_id, is_read, type_user_id, user_id)
                SELECT * FROM
               	    (SELECT 'channel' AS type, NEW.channel_id AS type_id, NEW.channel_id AS channel_id,
               	    false AS is_read, NEW.user_id AS type_user_id,
               	    (SELECT user_id from channel WHERE channel_id = NEW.channel_id) AS user_id)
                AS temptable
                WHERE temptable.user_id <> NEW.user_id;
            END;
        """,
        "DROP TRIGGER follow_notification"
        )
    ]
