 # -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_modify_comment_notification'),
    ]

    operations = [
        migrations.RunSQL(
        "DROP TRIGGER comment_notification",
        """
            CREATE TRIGGER comment_notification AFTER INSERT ON comment
            FOR EACH ROW
            INSERT INTO notification (type, article_id,type_id, user_id, is_read, type_user_id)
            VALUES ('comment', NEW.article_id, NEW.article_id, (
                SELECT user_id from channel WHERE channel_id IN (
                    SELECT channel_id FROM article WHERE article_id = NEW.article_id)), false, NEW.user_id);
        """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER new_comment_notification AFTER INSERT ON comment
            FOR EACH ROW
            INSERT INTO notification (type, type_id, article_id, is_read, type_user_id, user_id)
            SELECT * FROM
                (SELECT 'comment' as type, NEW.article_id as type_id, NEW.article_id as article_id,
                false as is_read, NEW.user_id as type_user_id,
                (SELECT user_id from channel WHERE channel_id IN
                    (SELECT channel_id FROM article WHERE article_id = NEW.article_id)) as user_id)
            as temptable
            where temptable.user_id <> NEW.user_id;
            """,
            "DROP TRIGGER new_comment_notification"
        )
    ]
